### ISSUE TITLE
Deprecation warning in Node 22

### ISSUE THREAD

**Issue by jleider** [gulpjs/vinyl#161] opened 2024-06-27 20:16 UTC
### What were you expecting to happen?

There to be no deprecation warning.

### What actually happened?

```
(node:22108) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
    at cloneStats (/Volumes/Sources/node_modules/clone-stats/index.js:6:21)
    at File.clone (/Volumes/Sources/node_modules/vinyl/index.js:135:23)
    at Transform.stream._transform (/Volumes/Sources/node_modules/gulp-rename/index.js:23:29)
    at Transform._write (node:internal/streams/transform:171:8)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Transform.Writable.write (node:internal/streams/writable:502:10)
    at Pumpify.ondata (/Volumes/Sources/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at Pumpify.emit (node:events:520:28)
    at Pumpify.emit (node:domain:551:15)
```

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: MacOS 13.6.7
* node version (run `node -v`): v22.3.0
* yarn version (run `yarn -v`): 4.1.0
* gulp version (run `gulp -v`): CLI version: 2.3.0 -- Local version: 4.0.2

**Comment by phated** [comment] 2024-06-27 21:27
Duplicate of https://github.com/gulpjs/vinyl-fs/issues/354

**Closed by phated** 2024-06-27 21:27 UTC
